# Generated by https://smithery.ai. See: https://smithery.ai/docs/build/project-config
# Start from official Python image
FROM python:3.11-slim

# Prevent interactive prompts
ENV DEBIAN_FRONTEND=noninteractive

# Install Google Chrome for Selenium.
# The webdriver-manager library in Python will automatically download the correct ChromeDriver.
RUN apt-get update \
    && apt-get install -y --no-install-recommends \
       wget \
       gnupg \
    && wget -q -O - https://dl.google.com/linux/linux_signing_key.pub | gpg --dearmor -o /usr/share/keyrings/google-chrome-keyring.gpg \
    && echo "deb [arch=amd64 signed-by=/usr/share/keyrings/google-chrome-keyring.gpg] http://dl.google.com/linux/chrome/deb/ stable main" > /etc/apt/sources.list.d/google-chrome.list \
    && apt-get update \
    && apt-get install -y --no-install-recommends \
       google-chrome-stable \
    && rm -rf /var/lib/apt/lists/*

# Set working directory
WORKDIR /app

# Copy requirements and install Python dependencies
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Copy the application code
COPY . .

# Ensure the Python script is executable
RUN chmod +x main.py

# Expose port for FastAPI (when needed)
EXPOSE 8003

# Default command - can be overridden in docker-compose
ENTRYPOINT ["python", "main.py"]
CMD []